spring.application.name=demo
server.port=8000
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:db}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.hikari.maximum-pool-size=20
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
logging.level.root=WARN
