version: '3.9'

services:
  benchmark:
    build: 
      context: ./benchmark
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=postgres"
    # volumes:
    #   - ./:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8080/"
      start_period: 30s
      interval: 15s
      timeout: 10s
      retries: 10
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tester:
    image: locustio/locust
    volumes:
      - ./tests:/mnt/locust
      - ./tests/results/${test_type}:/home/locust/
    command: >
      -f /mnt/locust/${test_type}.py 
      --csv benchmark 
      --run-time ${LOCUST_RUNTIME} 
      --headless 
      --users ${LOCUST_USERS} 
      --spawn-rate ${LOCUST_SPAWN_RATE} 
      -H http://benchmark:8080
      ${LOCUST_ARGS}
  # ports:
    #   - 8089:8089
    depends_on:
      benchmark:
        condition: service_healthy
volumes:
  pgdata: {}