services:
  db:
    image: postgres
    restart: always
    # volumes:
    #   # - ./data/db:/var/lib/postgresql/data
    #   # - ./pg_hba.conf:/var/lib/foo/pg_hba.conf
    # command: postgres -c hba_file=/var/lib/foo/pg_hba.conf 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      # - DB_NAME=test
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,dbuser
      - AUTH_TYPE=scram-sha-256
      - MAX_CLIENT_CONN=1000
    # ports:
    #   - "5432:5432"
    depends_on:
      - db
    healthcheck:
      test: "pg_isready --host localhost  -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5
  benchmark:
    restart: always
    build: 
      context: ./benchmark
      dockerfile: ./Dockerfile
    volumes:
      - "/app/notes/migrations/"

    ports:
      - "${PORT:-8000}:8000"

    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=pgbouncer
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8000/"
      start_period: 30s
      interval: 15s
      timeout: 10s
      retries: 10
    depends_on:
      pgbouncer:
        condition: service_healthy
      db:
        condition: service_healthy
  tester:
    image: locustio/locust
    volumes:
      - ./tests:/mnt/locust
      - ./tests/results:/home/locust/
    command: >
      -f /mnt/locust/locustfile.py 
      --csv benchmark 
      --run-time ${LOCUST_RUNTIME} 
      --headless 
      --users ${LOCUST_USERS} 
      --spawn-rate ${LOCUST_SPAWN_RATE} 
      -H http://benchmark:8000
    # ports:
    #   - 8089:8089
    depends_on:

      benchmark:
        condition: service_healthy
